### ISSUE TITLE
epub-metadata-editor does not cleanly close/exit ... continues to chew-up CPU

### ISSUE THREAD

**Issue by Chem101** [benchen71/epub-metadata-editor#55] opened 2021-01-04 03:33 UTC
After opening, using **_epub-metadata-editor_** and then exiting the program ... the program continues to use approximately 25% of the CPU !  

See screenshot via **_Process Explorer_** below.
![Capture](https://user-images.githubusercontent.com/76929412/103498580-6700ca80-4e99-11eb-854d-5b85a0245cff.PNG)

**_Otherwise, a great & very useful program.  Cheers from Australia._**

**Comment by benchen71** [comment] 2021-01-04 03:43
I have not seen this occurring myself. Does it happen every time? Does it eventually close?

Not sure how to go about debugging this problem. If it was related to a specific EPUB file, I usually ask people to include the EPUB. But this problem is more likely caused by some other program on your computer interfering with the running of EPubMetadataEditor. My program checks the internet for possible updates, so maybe a firewall is blocking it, causing that thread to wait?

**Comment by Chem101** [comment] 2021-01-04 04:02
Ben, thanks for the quick reply.  I completely uninstalled EME v. 1.8.4 via Revo Uninstaller which removed all fragments.  Downloaded your Portable version and it works perfectly ... doesn't chew-up CPU at all. 

For your interest, the below screenshot shows the old installation still running after close/exit and then I "killed" the EME process using Process Explorer.  The dramatic fall in CPU is clear.

![Capture2edit](https://user-images.githubusercontent.com/76929412/103499865-ac26fb80-4e9d-11eb-9c8b-8126b636272c.png)


**_Thanks again for a great program._**

**Comment by Chem101** [comment] 2021-01-04 04:16
Sorry, clicked the wrong button.

**Comment by benchen71** [comment] 2021-01-04 04:40
That's fine. As I said, I have not experienced this problem. I will put it down to a system-specific issue and close this.
(If anyone else is experiencing the problem, please let me know and I can reopen it.)

**Closed by benchen71** 2021-01-04 04:40 UTC

**Comment by benchen71** [comment] 2021-01-04 11:02
Actually, it's worth noting that the portable version is exactly the same executable as the installed version. If you are not seeing the same behaviour with the portable version, it's probably because it's located in a different folder.

**Comment by Chem101** [comment] 2021-01-04 12:16
Ben, I have remained curious about this problem and just tried to open the epub which caused the havoc last night.  Result:  Same problem with the EME Portable !
 
If the epub is drag & dropped onto the desktop icon, EME will remain closed, BUT in the background this causes a hidden EME process to chew-up ~25% CPU with each attempt, i.e., two attempts result in two separate EME processes hidden in the background.
 
Here's screen shot of Process Explorer's entries for two EME attempts = 50% CPU !

![ScreenShot001](https://user-images.githubusercontent.com/76929412/103533697-b10d9e80-4ee1-11eb-90a8-48f7c7015914.jpg)

I've attached the epub file for your reference. I have been using EME for about a month and this is the only epub file which caused havoc.  The nasty bit is this bad behaviour is hidden and it's deadly ... last night four attempts at opening this problematic epub resulted in near total collapse of my PC, i.e., ~ 100% CPU chew-ed up !
 
If this happens in future, I will immediately use Process Explorer to kill the EME process and edit the epub's metadata using Calibre.  Oddly, the problematic epub opened pre-edit in Calibre Reader without any problem.

Thanks Again.

[The Glory and the Dream - A Narrative History of America (1932-72) - Wm. Manchester.epub.zip](https://github.com/benchen71/epub-metadata-editor/files/5764546/The.Glory.and.the.Dream.-.A.Narrative.History.of.America.1932-72.-.Wm.Manchester.epub.zip)

**Comment by benchen71** [comment] 2021-01-04 22:36
There's a problem with one of the images in the EPUB: 00021.jpeg. I don't know if the problem is with the file itself or the way it has been stored in the EPUB. But I couldn't extract it using 7-Zip - it gave a CRC failed error. Deleting the file in the EPUB (using 7-zip) was possible and then the EPUB opens fine in EPubMetadataEditor.

Interestingly, in the temp folder that EPubMetadataEditor unzips the content, the problem image appears as follows:
![00021](https://user-images.githubusercontent.com/6054381/103586309-eee9e180-4f38-11eb-864c-3418e46a17e6.jpeg)

I might be able to do something to provide an error message. But that code is part of the ZIP library, which I am not responsible for...

**Comment by Chem101** [comment] 2021-01-04 23:41
Great forensics, Ben.  

I am curious whether the corrupt epub causes the same devastating CPU effect on your PC.  If you drag & drop the epub onto the EME desktop icon does it seemingly do nothing, BUT covertly generates a background process with each attempt which chews-up significant CPU % ?

Cheers, Lou

**Comment by benchen71** [comment] 2021-01-05 00:16
Yes, it did. Basically, the program goes into an infinite loop, so the operating system is left waiting for the process to end, but it never does (unless you do so manually).

When I opened the EPUB in EPubMetadataEditor running in Visual Basic, Visual Basic correctly identified that an infinite loop was occurring. I then traced through the program as it opened the EPUB file to try and work out what was going on.

I have added a line to the ZIP library code that stops the infinite loop from occurring. However, the resulting error that is shown to the user is not very helpful. It does, however, specify which file caused the problem. Interestingly, you can open the EPUB in Calibre. But when you view the book and go to the place where the image should be, it is simply not shown. So clearly Calibre's ZIP library is more robust in that it can handle the bad file without choking. Consequently, I might continue working on this issue, to more closely mirror this behaviour.

**Comment by Chem101** [comment] 2021-01-05 00:28
Thanks for the behavioural confirmation.

EME is a unique & very useful program and your avid willingness to iron-out glitches is greatly appreciated by its users.  I look forward to using updated versions of EME.

**Comment by benchen71** [comment] 2021-01-05 00:49
Anything for a fellow Aussie!

**Comment by benchen71** [comment] 2021-01-05 01:27
Version 1.8.5 can now open the file, giving an appropriate message to the user concerning the problematic file. You can also make changes to the metadata. When you save the file, the partial image is saved, too.

The upshot of this is that when you open the saved file in Calibre's viewer, instead of no image being shown (which was the behaviour before), you now see the partial image. I don't know if this is an improvement or not.

**Comment by Chem101** [comment] 2021-01-05 02:12
Just tested EME 1.8.5 (Portable version) on the corrupt EPUB file.  I can confirm EME 1.8.5 behaves impeccably, i.e., displays Error Warning; consumes negligible CPU %; cleanly closes and leaves no lingering background process.

**_Kudos !_**

**Comment by Chem101** [comment] 2021-01-05 02:38
**_Oh ... I forgot to award you the prestigious Koala stamp for your service to eBook readers._**

![Koala Stamp](https://user-images.githubusercontent.com/76929412/103600298-2d909380-4f5b-11eb-93e1-e3c599029fc3.jpg)
