### ISSUE TITLE
batch editing breaks images in epub

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#69] opened 2022-01-12 14:02 UTC
Alright, here is the rundown. 
- Batch editing 2 or more files.
- Replacing a field (in my tests I used source) with an empty string. 
- some specific files just break entirely, and my reader (readera, android app) just fails to load images entirely. 
I can't seem to find any kind of consistency with this bug. I've run tests with epub2 and epub3 in the batch edit lineup, but only specific books break (all are epub3s, but not all epub3s break)
I've also tried using this "fix cover" button, not sure what it does, but it doesn't help.
Somehow, single edit seems to work perfectly fine. 

I've tried checking the OPF file but can't seem to find any difference in the formatting that could hinder images from loading.
I've added the links to the batch of epubs that I tried editing as a file share link on google drive. 
(book 6 won't corrupt. book 7 and 8 will corrupt if put in a batch edit of 2 epubs or more.)
https://drive.google.com/file/d/1-64iMGsDZEGY1oaPd_8GCNvLv_QwvRYf/view?usp=sharing
https://drive.google.com/file/d/1-6ghujezFvJvSRBcyA4WhRp1xABUmi02/view?usp=sharing
https://drive.google.com/file/d/1-CiHW7m3jBlaRfgU9APCEmogK86wHZmE/view?usp=sharing

If there is any suspicions or things I could test, please let me know. i have no idea how to test because I have no idea what happens due to the lack of any consistency or reasoning.

**Comment by benchen71** [comment] 2022-01-13 06:22
I could see nothing obvious from my initial test run. The only thing I could see from a before/after comparison was that the id is being stripped from the title tag. But that shouldn't affect images.

When you say images fail to load, are you referring to the cover image?

**Comment by TheCrappyCompletionist** [comment] 2022-01-14 11:19
not just the cover image, no. All images in the whole document get replaced with a white square placeholder.

**Comment by benchen71** [comment] 2022-01-16 07:49
OK, I have absolutely no idea why your reader can't view images properly. I don't think anything significant has been changed at all. However, I have taken the opportunity to update the code to better handle title file-as information. Here's a pre-release 1.9.1. Give it a try and see what happens.
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/149651800-6a02a644-917c-461c-ac01-bcd2264b809d.jpg)
I was testing the output of batch edited files and they were displaying correctly in Calibre's ereader.

**Comment by TheCrappyCompletionist** [comment] 2022-01-16 08:23
I'm just as confused as you are. The editor doesn't touch anything but the metadata, so how will the images be affected? 
I did a comparison with my file backups, and the original works fine but after editing the metadata of the files they show up blank. Here's a screenshot of the books:
![screenshot](https://user-images.githubusercontent.com/91967427/149652600-775efdf0-8d70-4e5a-86fb-8c9d5f58e552.png)

![12345](https://user-images.githubusercontent.com/91967427/149652663-90291e62-9e8e-4c64-bf77-28371506c44e.jpg)

**Comment by benchen71** [comment] 2022-01-16 09:55
Try loading the bad ones into Calibre, do a save, and then try them in your reader. It will be interesting to see if Calibre can fix them. I can then take a look at the three OPF files: original, after EPUBMetadataEditor, and after Calibre.

**Comment by TheCrappyCompletionist** [comment] 2022-01-20 11:37
calibre is able to fix it. Here are the files: (7 and 8 are broken, 9 is working fine)
https://drive.google.com/file/d/11AOvhLYHDCQKpwhq9NhX5BhXXEkc6w-h/view?usp=sharing, https://drive.google.com/file/d/1VOoJ0FrYdowrOHjCNMqqZP0urmf7ExxL/view?usp=sharing, https://drive.google.com/file/d/1fq1ejLnKjPgOtgxNKxyizTv5BSNG12G3/view?usp=sharing

I dislike using calibre though because no matter what I try, the sorting order gets thrown out completely. Even just saving an already edited file makes the sorting of books go out of whack.

**Comment by benchen71** [comment] 2022-01-24 08:34
I will get back to this at some stage, but I'm back at work now, so it might be a while. Sorry!

**Comment by benchen71** [comment] 2022-01-24 08:36
Actually, if you can provide me with three versions of the same file, that would be super helpful: 1. original; 2. after EPUBMetadataEditor has broken the images; and 3. after Calibre has fixed it. Thanks.

**Comment by TheCrappyCompletionist** [comment] 2022-01-24 12:19
> 

that's what I've done with the 3 links above. They're Zip files, each containing a copy of volume 7, 8 and 9. the first link has the 3 before editing, the second link has the 3 after editing with the editor, and the third link has all 3 volumes after calibre has fixed it. sorry for my bad wording.

**Comment by benchen71** [comment] 2022-01-24 23:41
Brilliant! Thanks for doing that. That makes me far more keen to take a look and get to the bottom of this bug!

**Comment by benchen71** [comment] 2022-01-26 02:24
That did not exactly clear it up for me. I've tried something, but I have no idea if this will do the trick or not. Here's a pre-release 1.9.1 for you to try:
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/151093408-06bc3bec-5714-4ab8-a758-e76d4a1d5e29.jpg)

**Comment by TheCrappyCompletionist** [comment] 2022-01-29 13:27
sorry for the late response - work has been taking any free time I had this week.
There seems to be no change with the new version. The images just don't load. 
I wish there were more I could say, but I can't seem to find any kind of consistency or reason for this happening.

**Comment by benchen71** [comment] 2022-02-03 05:42
At this point I'm going to close this issue. Because the problem is only occurring with opening EPUBs in one specific viewer, there isn't really anything I can do. I don't know if the issue is with my program or with the viewer not handling something it should.

**Closed by benchen71** 2022-02-03 05:42 UTC
